---
title: "Zillow Real Estate Data By Zip Code(USA)" 
output: 
  flexdashboard::flex_dashboard:
    theme: cerulean
    social: ['facebook', 'linkedin','menu']
    orientation: rows
    navbar:
      - { title: "Predict Crypto Data Dashboard", href: "https://predictcrypto.shinyapps.io/24hData/" }
    source: embed
runtime: shiny

#Making this so I can work with easier example calculator
#TO-DO:
#Create map that actually shows something (like median prices color gradient. Forecasts might be even better!)
#Highlight points on the data-table on click
#For loop that finds biggest opportunities - button that once clicked gives zip codes with the lowest price per sqft (buy or rent) for the current filters

---

```{r setup, include=FALSE}
library(flexdashboard)
source("ZillowFormulas.R")
library(DT)
library(leaflet)
library(crosstalk)
options(scipen=999)
#crosstalk shared data
sd <- SharedData$new(data)
```

Inputs {.sidebar}
-----------------------------------------------------------------------

### [Zillow Research](https://www.zillow.com/research/data/)

```{r}
# selectInput("stateFilter", "State", choices = c("NO FILTER",unique(data$State)), multiple=F, selectize=TRUE, selected = "NY" )

#filter_select(id = 'stateFilter',label = 'State',sharedData = shared_df, group=data$State, allLevels = T)
filter_select("stateFilter", "State", sd, ~State)

```

*** 
**The data is grouped by the Zip code (one point per Zip).** <br/> <br/>
**This data is published by the Zillow Group and is updated and made publicly available [here](https://www.zillow.com/research/data/), where you can also find definitions for all of the variables. <br/> <br/> [Click here](https://www.zillow.com/research/about-us/) to learn more about Zillow Research** <br/> <br/>

**To remove the filter for State or City, select "NO FILTER" from the list of values (leaving these empty will generate an error)** <br/> <br/>

**Made by [Riccardo Esclapon](https://www.linkedin.com/in/esclaponriccardo/) in R Shiny. ** <br/> <br/>

**Not affilitated with Zillow Group in any way. **

Output {.tabset}
-----------------------------------------------------------------------

### Map

```{r}
if(is.null(sd$Longitude) != 1){
  sd %>% map()
}
```

### Scatterplot

```{r}
p <- ggplot(sd, aes(x=PriceToRentRatio, y=MedianPrice, 
                          text=paste("Metro:",sd$Metro, "\nCounty:",sd$County, "\nZip:",sd$Zip,
                                     "\nMedian Price($):",sd$MedianPrice,"\nMedian Price Per Square Feet($):",
                                     sd$MedianPricePerSqft,"\nZillow Home Value Index(ZHVI):",sd$Zhvi,
                                     "\nOne Year Forecast(% Change):",sd$ForecastYoYPctChange ), group=1)) +
             geom_jitter(mapping=aes(color=ForecastYoYPctChange), size=4, alpha=0.7) +
             #geom_point_interactive(aes(data_id=sd, onclick= sd$onclick)) +
             ggtitle(paste("Relationship between Median Price(y) and Price to Rent Ratio(x) color coded 
                           by Zillow Forecast(YoY)")) +
             scale_color_gradient(low="red", high="green") +
             #geom_smooth(method = lm) +
             labs(x="Price to Rent Ratio",y="Median Price($)",color="One Year Forecast(%Change)")

ggplotly(p, tooltip = "Zip") %>%
  highlight("plotly_selected") 
  # %>% highlight("plotly_click", color='red',persistent=T)
```

### 3d Chart

```{r}
sd %>% plot_ly(x =~PriceToRentRatio, y =~MarketHealthIndex, z = ~MedianPricePerSqft, color = ~ForecastYoYPctChange,colors=c("red","green")) %>%
    add_markers(opacity=0.7) %>%
    layout(title=paste("3d chart colored by Zillow Forecast(YoY)"), scene = list(xaxis = list(title = "Price to Rent Ratio"),
                                                                     yaxis = list(title = 'Market Health Index'),
                                                                     zaxis = list(title = 'Median Price Per Sqft($)')))
```


Row {data-height=250}
-----------------------------------------------------------------------

```{r}
sd %>% datatable(extensions='Buttons',options=list(
  dom = 'Blfrtip',
  buttons = c('colvis','copy','csv','excel','pdf','print'),
  lengthMenu = list(c(10,-1),c(10,'All')))) %>%
formatStyle("MedianPrice",backgroundColor = styleInterval(percentiles,c("red","yellow","green")),color = styleInterval(percentiles,c("white","blue","white"))) %>%
formatStyle("ForecastYoYPctChange",backgroundColor = styleInterval(percentiles2,c("red","yellow","green")),color = styleInterval(percentiles2,c("white","blue","white")))
```



